### ISSUE TITLE
python-ecdsa breaks compatibility

### ISSUE THREAD

**Issue by abitfan** [darkwallet/python-obelisk#21]
The latest release of python-ecdsa 
warner/python-ecdsa@80bdce1c0dd8d82134a7eda887cd7a54f7548d81 changed the number of arguments for ecdsa.curves.Curve which is used in https://github.com/darkwallet/python-obelisk/blob/master/obelisk/bitcoin.py line 315
I was going to re-write the code to check for ecdsa package version and change the number of arguments accordantly, but I thought I'd check here first.

Thoughts ?

**Comment by hoffmabc** [comment]
Yeah just found this out as well. I just submitted a PR upstream for this.

https://github.com/darkwallet/python-obelisk/pull/22

**Comment by veox** [comment]
Since it's fixed upstream, and the related PR is closed, this can be closed as well.
