### ISSUE TITLE
problem installing python

### ISSUE THREAD

**Issue by ashee69** [darkwallet/python-obelisk#24]
hello team, i am using kali linux 64 and i am explaining below problems with installation 
telling you everything step by step what i did and what i get
             # apt-get install python-pip python-twisted
          python-pip is already the newest version.
          python-twisted is already the newest version.

```
          # pip install ecdsa
        Requirement already satisfied (use --upgrade to upgrade): ecdsa in /usr/local/lib/python2.7/dist-packages
```

Cleaning up...

```
           # apt-get install cython
           Reading state information... Done
```

cython is already the newest version.
               and cython version Cython version 0.19.1

   then the next step 
                $ wget "https://github.com/zeromq/pyzmq/releases/download/v14.1.1/pyzmq-14.1.1.tar.gz"

```
             there was some problem there with downloading it in terminal
              Resolving s3.amazonaws.com (s3.amazonaws.com)... failed: Name or service not known.
               wget: unable to resolve host address `s3.amazonaws.com'

             so i downloaded it from from browser and followed again

             user@localhost:~$ cd Downloads
             user@localhost:~/Downloads$ tar xf pyzmq-14.1.1.tar.gz
             user@localhost:~/Downloads$ cd pyzmq-14.1.1
             user@localhost:~/Downloads/pyzmq-14.1.1$ 
             user@localhost:~/Downloads/pyzmq-14.1.1$ python setup.py configure --zmq=/usr/local/
   so i get here this : 

running configure
```

---

  Configure: Autodetecting ZMQ settings...
    Custom ZMQ dir:       /usr/local/
creating build/temp.linux-x86_64-2.7/scratch/tmp
cc -c /tmp/timer_create6xr9T9.c -o build/temp.linux-x86_64-2.7/scratch/tmp/timer_create6xr9T9.o
cc build/temp.linux-x86_64-2.7/scratch/tmp/timer_create6xr9T9.o -o build/temp.linux-x86_64-2.7/scratch/a.out
build/temp.linux-x86_64-2.7/scratch/tmp/timer_create6xr9T9.o: In function `main':
timer_create6xr9T9.c:(.text+0x15): undefined reference to`timer_create'
collect2: error: ld returned 1 exit status
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/temp.linux-x86_64-2.7/scratch/vers.c -o build/temp.linux-x86_64-2.7/scratch/vers.o
build/temp.linux-x86_64-2.7/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory
compilation terminated.

error: command 'gcc' failed with exit status 1

Fatal: Falling back on bundled libzmq, but setup.cfg has explicitly prohibited building the libzmq extension.

please help what shall i do next.
thank you.

**Comment by veox** [comment]
The instructions in `INSTALL` assume you're building `python-obelisk` for use with the Darkwallet `gateway` (I know, since I wrote them :/).

Does your system have `zmq.h`?

Try installing `libzmq` from your distribution package manager (if you're indeed not doing this for `obelisk` or `libbitcoin-server`).

If that doesn't work, you could try something like the instructions on [the wiki](https://wiki.unsystem.net/en/index.php/Install_entire_toolchain), although that won't necessarily work.

**Comment by ashee69** [comment]
hello veox, thanks for your reply. zerromq has solved the issue.
additionally can you please take a look what problems i am getting in darkleaks
 the issue is i totally misunderstood it how to use.
i have rightly done every installation step.
now when i put command
$ .gui-start.sh
then this screen comes up to me
http://gyazo.com/d7d7adecdb27ecd17019e13611371dee

i didnt have much knowledge about those chunk n all though i went ahead with filling all info
then i took me here
http://gyazo.com/0bd82998aaee9220784793eb4e69db41

please tell me some things :
suppose if i am possessing credit card details of someone then how can i sell there, and who will decide the price, and in which format should it be in the text file.

suppose if i am a buyer then where i can look what people are selling
and please tell me also about chunk and to reveal them
thanx in advance

**Comment by veox** [comment]
This issue is not relevant to `python-obelisk`, so I suggest you ask this on the Darkleaks issue tracker.

I haven't used Darkleaks myself, so can't really help you here.

**Comment by ashee69** [comment]
yes i posted there issue, but seems like noone is responding there thats  why i asked .
btw thanks for ur response
